services:
  db:
    image: postgres:15
    container_name: kanban_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"

volumes:
  postgres_data: